version: "3"

services:
  php:
    build: ./docker/
    volumes: 
    - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - "TEST=test"

  db:
    image: "mariadb:10"
    environment: 
    - "MYSQL_ROOT_PASSWORD=example"
    - "MYSQL_DATABASE=tematres"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on: 
      - db


